### ISSUE TITLE
suggestion: add CI checks

### ISSUE THREAD

**Issue by iuioiua** [BlackAsLight/encoding-stream#3]
I suggest adding CI checks, like formatting and linting checks and tests, to ensure all PRs are up to your standards and don't break anything.

**Comment by BlackAsLight** [comment]
I do need to make some tests, that always tends to be an afterthought. For the linting, I'll need to look into it as it's new to me and seems to offer a lot.

**Comment by BlackAsLight** [comment]
3076754085f0b8d81734771a4b203dd5fab273f1
