### ISSUE TITLE
suggestion: add examples for each symbol

### ISSUE THREAD

**Issue by iuioiua** [BlackAsLight/encoding-stream#4]
It may seem redundant, given you already have an example in the module documentation, but doing so allows symbols to be better understood. E.g. see https://jsr.io/@doctor/encoding-stream/doc/base32/~/DecodeBase32Stream.

**Comment by BlackAsLight** [comment]
This does sound like a great idea.

**Comment by BlackAsLight** [comment]
3076754085f0b8d81734771a4b203dd5fab273f1
