### ISSUE TITLE
suggestion: use Deno's in-built formatter

### ISSUE THREAD

**Issue by iuioiua** [BlackAsLight/encoding-stream#5]
This means contributors don't have to download another tool they may not already have. You can migrate Prettier's settings to Deno's formatter settings. See https://docs.deno.com/runtime/manual/getting_started/configuration_file#fmt

**Comment by BlackAsLight** [comment]
Deno's fmt doesn't have as many features as I'd like, but it does seem to have a bit more than I remember so I'll look into it later.

**Comment by BlackAsLight** [comment]
3076754085f0b8d81734771a4b203dd5fab273f1
